ALTER TABLE engineering_profiles
ADD COLUMN rms_target DOUBLE PRECISION,
ADD COLUMN rms_tolerance DOUBLE PRECISION,
ADD COLUMN peak_target DOUBLE PRECISION,
ADD COLUMN peak_tolerance DOUBLE PRECISION,
ADD COLUMN noise_target DOUBLE PRECISION,
ADD COLUMN noise_tolerance DOUBLE PRECISION,
ADD COLUMN distortion_target DOUBLE PRECISION,
ADD COLUMN distortion_tolerance DOUBLE PRECISION;
